#
# Module manifest for module 'DSC.PipelineRunner.Akkodis'
#
# Generated by: Michael Zanatta
#
# Generated on: 10/10/2024
#

@{

    Path = "./DSC.PipelineRunner.Akkodis.psd1"
    ModuleManifest = "./DSC.PipelineRunner.Akkodis.psd1"
    # Script module or binary module file associated with this manifest.

}

