name: Perform Development Build

on:
  workflow_dispatch:
  push:
    branches:
      - Development

jobs:

  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Step 1 - Download PowerShell Dependencies
        shell: pwsh
        run: Install-Module Datum, Datum.InvokeCommand, powershell-yaml, PSDesiredStateConfiguration -Force

      - name: Step 2 - Attempt to Build the Project
        shell: pwsh
        run: .\Build.ps1 -ResolveDependency -Tasks build -CodeCoverageThreshold 70 -PesterScript .\tests.ps1

      - name: Step 3 - Package the Project
        shell: pwsh
        run: .\Build.ps1 -Tasks pack

      - name: Step 4 - Set Version Number
        shell: bash
        run: echo "BUILD_VERSION=$(cat ./output/version.txt)" >> $GITHUB_OUTPUT

      - name: Step 4 - Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.run_id }}
          path: ./output/azdo-dsc-lcm/

  release:
    runs-on: ubuntu-latest
    needs: build
    env:
      BUILD_VERSION: ${{ needs.build.outputs.build-version }}
    steps:
      - name: Step 0 - Print Version
        shell: pwsh
        run: write-host $("${{ env:BUILD_VERSION }}-${{ github.run_number }}")

      - name: Step 1 - Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.run_id }}

      - name: Step 2 - Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ github.repository }} - ${{ env:BUILD_VERSION }}-${{ github.run_number }}
          tag_name: ${{ env:BUILD_VERSION }}-${{ github.run_number }}

